name: Build & Deploy API

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                  
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Create .env from GitHub secrets
              run: |
                echo "DB_ENDPOINT=${{ secrets.DB_ENDPOINT }}" >> .env
                echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
                echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
                echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
                echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
           
            - name: List files in the working directory
              run: ls -alh

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                # Hacer push a docker hub de la imagen recien construida
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/ventas_api:latest
                context: .
                file: ./Springboot-API-REST/Dockerfile
        

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login SSH on EC2 to Deploy
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_IP_REMOTE }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }}
                port: ${{ secrets.EC2_SSH_PORT }}
                script: |
                  mkdir -p /home/ubuntu/ventas/
                  ls -la
                  pwd
                  cd /home/ubuntu/ventas/
                  # Instalación de Docker y Docker Compose (si no están instalados)
                  sudo apt update -y
                  sudo apt install -y docker.io docker-compose
                  # Hacer un pull de la imagen de docker hub
                  docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ventas_api:latest
                  # Ejecutar el contenedor en segundo plano
                  docker run -d -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/ventas_apilatest
            
