name: Build & Deploy API

on:
  repository_dispatch:
    types:
      - backend-ventas

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                  
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Create .env from GitHub secrets
              run: |
                echo "DB_ENDPOINT=${{ secrets.DB_ENDPOINT }}" >> .env
                echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
                echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
                echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
                echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
           
            - name: List files in the working directory
              run: ls -alh

            - name: Login to Docker Hub manually
              run: |
                echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                # Hacer push a docker hub de la imagen recien construida
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/ventas_api:latest
                context: ./Springboot-API-REST
                file: ./Springboot-API-REST/Dockerfile
        

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Instalar Doppler CLI
              uses: dopplerhq/cli-action@v3
  
            - name: Configurar Doppler CLI
              env:
                DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
              run: doppler setup --token $DOPPLER_TOKEN
  
  
            - name: Obtener secretos desde Doppler
              env:
                DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
              run: |
                echo "EC2_KEY=$(doppler secrets get EC2_KEY --plain)" >> $GITHUB_ENV
                echo "SERVIDOR_VENTAS=$(doppler secrets get SERVIDOR_VENTAS --plain)" >> $GITHUB_ENV


            - name: Login SSH on EC2 to Deploy
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ env.SERVIDOR_VENTAS }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.SSH_KEY_CITT }}
                port: ${{ secrets.EC2_SSH_PORT }}
                script: |
                  mkdir -p /home/ubuntu/ventas/
                  cd /home/ubuntu/ventas/
                  # Instalación de Docker y Docker Compose (si no están instalados)
                  sudo apt update -y
                  sudo apt install -y docker.io docker-compose
                  # Hacer un pull de la imagen de docker hub
                  sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ventas_api:latest
                  # Ejecutar el contenedor en segundo plano
                  sudo docker run -d -p 8080:8080 \
                    -e "DB_ENDPOINT=${{ secrets.DB_ENDPOINT }}" \
                    -e "DB_PORT=${{ secrets.DB_PORT }}" \
                    -e "DB_NAME=${{ secrets.DB_NAME }}" \
                    -e "DB_USERNAME=${{ secrets.DB_USERNAME }}" \
                    -e "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
                    ${{ secrets.DOCKERHUB_USERNAME }}/ventas_api:latest
